import { execSync } from "child_process";
import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from "fs";
import { join } from "path";
import type { MemoryEngine } from "./engine.js";

// MARK: - Memory Freshness Manager

export interface FreshnessReport {
  name: string;
  zone: string;
  daysSinceUpdate: number;
  gitCommitsSince: number;
  status: "fresh" | "warning" | "stale";
  affectedFiles: string[]; // Changed files that relate to this memory
}

/**
 * Automatically check memory freshness against git changes.
 * Runs on gateway startup and can be triggered periodically.
 *
 * When stale memories are detected, marks them with a [STALE] prefix
 * in the SPATIAL_INDEX.jcross and optionally triggers regeneration.
 */
export class FreshnessManager {
  private memory: MemoryEngine;
  private projectRoot: string;
  private checkIntervalMs: number;
  private timer: ReturnType<typeof setInterval> | null = null;

  constructor(
    memory: MemoryEngine,
    projectRoot: string,
    checkIntervalMs = 5 * 60 * 1000 // 5 minutes default
  ) {
    this.memory = memory;
    this.projectRoot = projectRoot;
    this.checkIntervalMs = checkIntervalMs;
  }

  // MARK: - Auto Check

  /**
   * Start periodic freshness checks.
   * Called on gateway startup.
   */
  startPeriodicCheck(): void {
    // Immediate check on start
    this.checkAndMark();

    // Periodic check
    this.timer = setInterval(() => {
      this.checkAndMark();
    }, this.checkIntervalMs);
  }

  stopPeriodicCheck(): void {
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
  }

  // MARK: - Check All Memories

  checkAll(): FreshnessReport[] {
    const reports: FreshnessReport[] = [];
    const entries = this.memory.list();

    for (const entry of entries) {
      const daysSince = Math.floor(
        (Date.now() - entry.modified.getTime()) / (1000 * 60 * 60 * 24)
      );

      const { commitCount, changedFiles } = this.getGitChanges(
        entry.modified
      );

      // Determine which changed files relate to this memory
      const affectedFiles = this.findAffectedFiles(entry.name, changedFiles);

      let status: FreshnessReport["status"] = "fresh";
      if (affectedFiles.length > 0 || commitCount > 10) {
        status = "stale";
      } else if (commitCount > 3) {
        status = "warning";
      }

      reports.push({
        name: entry.name,
        zone: entry.zone,
        daysSinceUpdate: daysSince,
        gitCommitsSince: commitCount,
        status,
        affectedFiles,
      });
    }

    return reports;
  }

  // MARK: - Check and Mark Stale

  /**
   * Check freshness and update SPATIAL_INDEX.jcross with stale markers.
   * Also writes a freshness_report.md to front/ for agent visibility.
   */
  checkAndMark(): FreshnessReport[] {
    const reports = this.checkAll();
    const staleReports = reports.filter((r) => r.status === "stale");
    const warningReports = reports.filter((r) => r.status === "warning");

    if (staleReports.length === 0 && warningReports.length === 0) {
      // Remove old freshness report if everything is fresh
      this.memory.delete("freshness_report");
      return reports;
    }

    // Write freshness report to front/ so it gets injected into prompts
    const timestamp = new Date().toISOString();
    const reportContent = `---
name: Freshness Report
description: Auto-generated report of stale memories. Check before trusting mid/ reports.
type: project
updated: ${timestamp}
---

# Memory Freshness Report
Generated: ${timestamp}

${staleReports.length > 0 ? `## ❌ Stale Memories (DO NOT TRUST without re-checking)
${staleReports
  .map(
    (r) =>
      `- **${r.zone}/${r.name}** — ${r.gitCommitsSince} commits behind, ${r.daysSinceUpdate}d old
  Affected files: ${r.affectedFiles.slice(0, 5).join(", ") || "general project changes"}`
  )
  .join("\n")}
` : ""}
${warningReports.length > 0 ? `## ⚠️ Possibly Outdated
${warningReports
  .map(
    (r) =>
      `- **${r.zone}/${r.name}** — ${r.gitCommitsSince} commits since last update`
  )
  .join("\n")}
` : ""}
## Action Required
Stale memories should be regenerated by running:
\`./verantyx-start.sh freshness\`
Or ask a worker agent to re-scan the affected files.
`;

    this.memory.write("front", "freshness_report", reportContent);

    return reports;
  }

  // MARK: - Git Integration

  private getGitChanges(since: Date): {
    commitCount: number;
    changedFiles: string[];
  } {
    try {
      const sinceStr = since.toISOString().split("T")[0];

      const countResult = execSync(
        `cd "${this.projectRoot}" && git log --oneline --since="${sinceStr}" --all 2>/dev/null | wc -l`,
        { encoding: "utf-8" }
      ).trim();
      const commitCount = parseInt(countResult) || 0;

      let changedFiles: string[] = [];
      if (commitCount > 0) {
        const filesResult = execSync(
          `cd "${this.projectRoot}" && git diff --name-only HEAD~${Math.min(commitCount, 50)}..HEAD 2>/dev/null || git diff --name-only --cached 2>/dev/null`,
          { encoding: "utf-8" }
        ).trim();
        changedFiles = filesResult
          .split("\n")
          .filter((f) => f.length > 0);
      }

      return { commitCount, changedFiles };
    } catch {
      return { commitCount: 0, changedFiles: [] };
    }
  }

  /**
   * Match changed files to memory entries.
   * e.g., if moutheat_structure.md exists and MouthEat-iOS/ files changed → stale
   */
  private findAffectedFiles(
    memoryName: string,
    changedFiles: string[]
  ): string[] {
    const patterns: Record<string, string[]> = {
      moutheat_structure: ["mouth-eat/", "MouthEat-iOS/"],
      mouthselect_structure: ["visionos-mouth-select/", "MouthSelect-iOS/"],
      verantyxface_structure: ["VerantyxFace-iOS/"],
      auth_unification: ["VerantyxAuth", "AuthManager", "AuthPrompt"],
      mouth_data_collection: ["MouthData", "MouthMovement", "MouthCollector"],
    };

    const matchers = patterns[memoryName];
    if (!matchers) return [];

    return changedFiles.filter((file) =>
      matchers.some((pattern) => file.includes(pattern))
    );
  }
}
