import re
from typing import List, Dict, Any

class JCrossExtractionParser:
    """
    Parses V7.1 JCross Semantic Fragments generated by the Puzzle IR Builder.
    """
    
    @staticmethod
    def parse(llm_output: str) -> List[Dict[str, Any]]:
        fragments = []
        current_frag = {}
        
        lines = llm_output.strip().split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                continue
                
            if line.startswith("■ JCROSS_FRAG_"):
                if current_frag:
                    fragments.append(current_frag)
                frag_id = line.replace("■ ", "").strip()
                current_frag = {"__id__": frag_id}
                continue
                
            if not current_frag:
                continue
                
            # Parse the fields
            if line.startswith("【源泉】"):
                current_frag["source"] = line.replace("【源泉】", "").strip()
            elif line.startswith("【主体】"):
                current_frag["subject"] = line.replace("【主体】", "").strip()
            elif line.startswith("【関係】"):
                current_frag["predicate"] = line.replace("【関係】", "").strip()
            elif line.startswith("【客体】"):
                current_frag["object"] = line.replace("【客体】", "").strip()
            elif line.startswith("【文脈】"):
                current_frag["context"] = line.replace("【文脈】", "").strip()
            elif line.startswith("【状態】"):
                current_frag["state"] = line.replace("【状態】", "").strip()
            elif line.startswith("【軌道】"):
                track_val = line.replace("【軌道】", "").strip()
                trace_match = re.search(r"\[遡:\s*(.+?)\]", track_val)
                if trace_match:
                    current_frag["trace"] = trace_match.group(1).strip()
                else:
                    current_frag["trace"] = None
                    
        if current_frag:
            fragments.append(current_frag)
            
        return fragments
